/**
 * The wire protocol.
 *
 * Plain WebSocket with a zod-validated message envelope, per PLAN.md — no game
 * server framework, because Cities & Knights in M7 needs full control over
 * phase logic and redaction.
 *
 * Direction matters for trust. Client to server is hostile input and is parsed
 * strictly. Server to client is generated by us; the schema exists so tests can
 * assert the shape and so a client can fail loudly on a version mismatch.
 */

import { z } from "zod";
import type { Action, GameEvent, PlayerId, PlayerView } from "@hexport/engine";
import { actionSchema } from "./action.js";

export const PROTOCOL_VERSION = 1;

const nickname = z
  .string()
  .trim()
  .min(1)
  .max(24)
  // Printable, no control characters. Chat and names are rendered as text.
  .regex(/^[^\p{C}]+$/u, "Nickname contains control characters");

/** Room codes are short, unambiguous and case-insensitive on the way in. */
export const ROOM_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const roomCode = z
  .string()
  .trim()
  .toUpperCase()
  .length(5)
  .regex(/^[A-Z0-9]+$/);

// ---------------------------------------------------------------------------
// Client to server
// ---------------------------------------------------------------------------

export const clientMessageSchema = z.discriminatedUnion("t", [
  /** First message on a fresh socket. A token resumes an existing seat. */
  z.object({
    t: z.literal("hello"),
    version: z.number().int(),
    token: z.string().min(1).max(200).optional(),
  }),
  z.object({
    t: z.literal("createRoom"),
    nickname,
    scenarioId: z.string().min(1).max(64).optional(),
    playerCount: z.number().int().min(2).max(6).optional(),
  }),
  z.object({ t: z.literal("joinRoom"), code: roomCode, nickname }),
  z.object({ t: z.literal("leaveRoom") }),
  z.object({ t: z.literal("setReady"), ready: z.boolean() }),
  z.object({ t: z.literal("startGame") }),
  z.object({ t: z.literal("command"), action: actionSchema }),
  /** Host only. */
  z.object({ t: z.literal("kick"), player: z.number().int().min(0).max(5) }),
  z.object({ t: z.literal("chat"), text: z.string().trim().min(1).max(400) }),
  z.object({ t: z.literal("ping") }),
]);

export type ClientMessage = z.infer<typeof clientMessageSchema>;

// ---------------------------------------------------------------------------
// Server to client
// ---------------------------------------------------------------------------

export interface RoomSeat {
  readonly player: PlayerId;
  readonly nickname: string;
  readonly connected: boolean;
  readonly ready: boolean;
  readonly isHost: boolean;
}

export interface RoomView {
  readonly code: string;
  readonly scenarioId: string;
  readonly seats: readonly RoomSeat[];
  readonly started: boolean;
  readonly you: PlayerId | null;
  readonly hostPlayer: PlayerId | null;
  readonly maxPlayers: number;
}

/**
 * The per-player view sent over the wire.
 *
 * The board is static for a match, so it ships once in the snapshot and updates
 * omit it.
 *
 * `legalMoves` is computed by the server and sent down. The client holds only a
 * redacted view, so it *cannot* run legalMoves() itself — it does not know the
 * development deck, the other hands, or the generator state. Sending the list
 * keeps CLAUDE.md golden rule 3 intact across the network: the UI still derives
 * every enabled control from legalMoves, it just no longer computes it locally.
 * A client that invents an option gets it rejected by the reducer anyway.
 */
export interface WireView extends Omit<PlayerView, "board"> {
  readonly legalMoves: readonly Action[];
}

export interface ChatLine {
  readonly from: string;
  readonly player: PlayerId | null;
  readonly text: string;
  readonly at: number;
}

/**
 * Turn timer state. PLAN.md asks for a turn timer with auto-pass; the deadline
 * is sent so every client counts down against the same wall clock rather than
 * each running its own.
 */
export interface TimerState {
  readonly player: PlayerId;
  /** Epoch milliseconds. */
  readonly deadline: number;
}

export type ServerMessage =
  | { readonly t: "welcome"; readonly version: number; readonly token: string }
  | { readonly t: "room"; readonly room: RoomView }
  | {
      readonly t: "snapshot";
      readonly board: PlayerView["board"];
      readonly view: WireView;
      readonly log: readonly GameEvent[];
      readonly chat: readonly ChatLine[];
      /** sha256 of the seed, published at game start (p. "Dice and fairness"). */
      readonly seedCommitment: string;
      readonly timer: TimerState | null;
    }
  | {
      readonly t: "update";
      readonly events: readonly GameEvent[];
      readonly view: WireView;
      readonly timer: TimerState | null;
    }
  | { readonly t: "chat"; readonly line: ChatLine }
  | {
      readonly t: "error";
      readonly message: string;
      readonly code: ErrorCode;
    }
  /** Published at game end so anyone can verify every roll. */
  | { readonly t: "seedRevealed"; readonly seed: string }
  | { readonly t: "pong" };

export type ErrorCode =
  | "bad-message"
  | "bad-version"
  | "no-room"
  | "room-full"
  | "room-started"
  | "not-host"
  | "not-seated"
  | "illegal-move"
  | "rate-limited"
  | "internal";

/** Parse untrusted client input. */
export function parseClientMessage(
  input: unknown,
): { ok: true; message: ClientMessage } | { ok: false; reason: string } {
  const result = clientMessageSchema.safeParse(input);
  if (!result.success) {
    const first = result.error.issues[0];
    return {
      ok: false,
      reason:
        first === undefined
          ? "Malformed message."
          : `${first.path.join(".") || "message"}: ${first.message}`,
    };
  }
  return { ok: true, message: result.data };
}

/** Decode a WebSocket frame into a client message. Never throws. */
export function decodeClientFrame(
  data: string,
): { ok: true; message: ClientMessage } | { ok: false; reason: string } {
  if (data.length > 64 * 1024) {
    return { ok: false, reason: "Message too large." };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(data);
  } catch {
    return { ok: false, reason: "Not valid JSON." };
  }
  return parseClientMessage(parsed);
}

export function encode(message: ServerMessage | ClientMessage): string {
  return JSON.stringify(message);
}
