import { describe, it, expect } from "vitest";
import { buildBoardGraph, seedRng, neighbors, tileId } from "@hexport/engine";
import { loadScenario } from "./index.js";
import type { Scenario } from "@hexport/engine";

/**
 * The Seafarers boards, against the rulebook's own composition tables.
 *
 * These boards are generated by scripts/generate-seafarers-scenarios.mjs, which
 * means a typo in a bag is a typo in a board that still parses, still builds and
 * still plays — just not the game the rulebook describes. schema.test.ts proves
 * only that they load. This file is what proves they are the right boards.
 *
 * Citations are to CN3083 Seafarers 2025: New Shores p.4, Through the Desert
 * p.10 (3 players) and p.11 (4 players).
 *
 * One deliberate divergence, recorded in ADR 0008: the *sea* counts do not match
 * the printed tables. The rulebook's sea count belongs to its own fixed island
 * outlines; ours are generated, so the frame of water around them is whatever
 * the shape needs. Every land figure below is the rulebook's exactly.
 */

interface Expectation {
  readonly id: string;
  /** Land terrain multiset, straight from the rulebook table. */
  readonly land: Readonly<Record<string, number>>;
  readonly sea: number;
  readonly discs: number;
  readonly ports: number;
  readonly generic: number;
  readonly victoryPoints: number;
}

const BOARDS: readonly Expectation[] = [
  {
    id: "new-shores-3",
    land: { hill: 4, forest: 3, pasture: 5, field: 4, mountain: 4, gold: 2 },
    sea: 16,
    discs: 22,
    ports: 8,
    generic: 3,
    victoryPoints: 14,
  },
  {
    id: "new-shores-4",
    // p.4: two gold, five of each terrain, one desert.
    land: {
      hill: 5,
      forest: 5,
      pasture: 5,
      field: 5,
      mountain: 5,
      desert: 1,
      gold: 2,
    },
    sea: 18,
    discs: 27,
    ports: 9,
    generic: 4,
    victoryPoints: 14,
  },
  {
    id: "through-the-desert-3",
    // p.10: two gold, three hills, five forest, four pasture, four fields,
    // four mountains, three deserts.
    land: { desert: 3, hill: 3, forest: 5, pasture: 4, field: 4, mountain: 4, gold: 2 },
    sea: 16,
    discs: 22,
    ports: 8,
    generic: 3,
    victoryPoints: 14,
  },
  {
    id: "through-the-desert-4",
    // p.11: two gold, five of each terrain, three deserts.
    land: {
      desert: 3,
      hill: 5,
      forest: 5,
      pasture: 5,
      field: 5,
      mountain: 5,
      gold: 2,
    },
    sea: 18,
    discs: 27,
    ports: 9,
    generic: 4,
    victoryPoints: 14,
  },
];

function tally(values: readonly string[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const value of values) counts[value] = (counts[value] ?? 0) + 1;
  return counts;
}

function landCount(expectation: Expectation): number {
  return Object.values(expectation.land).reduce((a, b) => a + b, 0);
}

describe.each(BOARDS)("$id", (expectation) => {
  const scenario: Scenario = loadScenario(expectation.id);
  const { board } = buildBoardGraph(scenario, seedRng(`${expectation.id}-fixed`));

  it("deals exactly the terrain the rulebook lists", () => {
    expect(tally(Object.values(board.tiles).map((t) => t.terrain))).toEqual({
      ...expectation.land,
      sea: expectation.sea,
    });
  });

  it("numbers every land hex but the deserts", () => {
    const numbered = Object.values(board.tiles).filter((t) => t.number !== null);
    expect(numbered).toHaveLength(expectation.discs);

    // The count above would also be satisfied by numbering a desert and leaving
    // some other hex bare, so check which hexes directly.
    for (const tile of Object.values(board.tiles)) {
      const bare = tile.terrain === "desert" || tile.terrain === "sea";
      expect(tile.number === null).toBe(bare);
    }
  });

  it("numbers the gold fields, which is what makes them worth taking", () => {
    const gold = Object.values(board.tiles).filter((t) => t.terrain === "gold");
    expect(gold).toHaveLength(expectation.land["gold"] ?? 0);
    for (const tile of gold) expect(tile.number).not.toBeNull();
  });

  it("wins at the scenario's own threshold, not at ten", () => {
    expect(scenario.victoryPoints).toBe(expectation.victoryPoints);
  });

  it("gives every player fifteen ships", () => {
    expect(scenario.pieces.ships).toBe(15);
  });

  it("opens on the main island only", () => {
    // New Shores p.3 and Through the Desert p.10 both say the starting
    // settlements must go on the main island. Four Islands (p.6) does not, which
    // is one reason it is not here.
    expect(scenario.setup.setupIslands).toEqual(["main"]);
  });

  it("pays two points for a first settlement on any island but the main one", () => {
    const byId = new Map(scenario.islands.map((i) => [i.id, i.vpForFirstSettlement]));
    expect(byId.get("main")).toBe(0);
    expect(byId.size).toBeGreaterThan(1);
    for (const [id, vp] of byId) {
      if (id !== "main") expect(vp).toBe(2);
    }
  });

  it("has five two-for-one ports, one per resource", () => {
    const ports = Object.values(board.ports);
    expect(ports).toHaveLength(expectation.ports);
    expect(ports.filter((p) => p.kind === "generic")).toHaveLength(expectation.generic);

    const resourcePorts = ports.filter((p) => p.kind === "resource");
    expect(resourcePorts.map((p) => p.resource).sort()).toEqual([
      "brick",
      "grain",
      "lumber",
      "ore",
      "wool",
    ]);
    for (const port of resourcePorts) expect(port.ratio).toBe(2);
    for (const port of ports.filter((p) => p.kind === "generic")) {
      expect(port.ratio).toBe(3);
    }
  });

  it("is a sea board, so ships have somewhere to go", () => {
    const kinds = tally(Object.values(board.edges).map((e) => e.kind));
    // A board with no coast edge would accept no ship at all, and a board with
    // no sea edge would let ships go nowhere once launched.
    expect(kinds["coast"] ?? 0).toBeGreaterThan(0);
    expect(kinds["sea"] ?? 0).toBeGreaterThan(0);
  });

  it("puts every land hex on a declared island", () => {
    const declared = new Set(scenario.islands.map((i) => i.id));
    let land = 0;
    for (const tile of Object.values(board.tiles)) {
      if (tile.terrain === "sea") continue;
      land++;
      expect(declared).toContain(tile.island);
    }
    expect(land).toBe(landCount(expectation));
  });

  it("never puts a 6 next to an 8, across fifty seeds", () => {
    for (let i = 0; i < 50; i++) {
      const { board: b } = buildBoardGraph(
        scenario,
        seedRng(`${expectation.id}-sweep-${String(i)}`),
      );
      for (const tile of Object.values(b.tiles)) {
        if (tile.number !== 6 && tile.number !== 8) continue;
        for (const n of neighbors(tile.coord)) {
          const other = b.tiles[tileId(n)];
          if (other === undefined || other.number === null) continue;
          expect([6, 8]).not.toContain(other.number);
        }
      }
    }
  });

  it("keeps its terrain multiset no matter the seed", () => {
    const expected = { ...expectation.land, sea: expectation.sea };
    for (let i = 0; i < 20; i++) {
      const { board: b } = buildBoardGraph(
        scenario,
        seedRng(`${expectation.id}-shuffle-${String(i)}`),
      );
      expect(tally(Object.values(b.tiles).map((t) => t.terrain))).toEqual(expected);
    }
  });

  it("builds byte-identically from the same seed", () => {
    const a = buildBoardGraph(scenario, seedRng("repeat")).board;
    const b = buildBoardGraph(scenario, seedRng("repeat")).board;
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
  });
});

describe("the Seafarers boards as a set", () => {
  it("all load the seafarers module, which is what turns ships on", () => {
    for (const { id } of BOARDS) {
      expect(loadScenario(id).modules).toEqual(["base", "seafarers"]);
    }
  });

  it("puts the gold on the outer islands, where it is worth sailing to", () => {
    // Through the Desert only: p.11 puts both gold fields out among the regions
    // rather than on the main island, which is the whole reason to leave home.
    for (const id of ["through-the-desert-3", "through-the-desert-4"]) {
      const scenario = loadScenario(id);
      const { board } = buildBoardGraph(scenario, seedRng(`${id}-gold`));
      for (const tile of Object.values(board.tiles)) {
        if (tile.terrain !== "gold") continue;
        expect(tile.island).not.toBe("main");
      }
    }
  });

  it("keeps the deserts on the main island, where they split it", () => {
    // p.10: the deserts are what the scenario is named for — they cut the main
    // island in two, so they must be on it.
    for (const id of ["through-the-desert-3", "through-the-desert-4"]) {
      const { board } = buildBoardGraph(loadScenario(id), seedRng(`${id}-desert`));
      const deserts = Object.values(board.tiles).filter((t) => t.terrain === "desert");
      expect(deserts).toHaveLength(3);
      for (const tile of deserts) expect(tile.island).toBe("main");
    }
  });
});
